### PR TITLE
Added app icon

### PR DESCRIPTION
**Pull request by sante**
Emulator menu with Gong icon:

### CODE REVIEW

**Review by f7deleon — APPROVED** [review]
Maybe add an image of the app icon?

**Comment by f7deleon** [comment]
> Emulator menu with Gong icon:
> 

 lol great icon

**Review by f7deleon — APPROVED** [review]

**Comment by miduch** [comment]
how about adding ribbon to app launcher icon as well? :) 

https://medium.com/@cycki/ribbonize-your-android-application-laucher-icon-again-c52e08d58172

**Comment by f7deleon** [comment]
> how about adding ribbon to app launcher icon as well? :)
> 
> https://medium.com/@cycki/ribbonize-your-android-application-laucher-icon-again-c52e08d58172

We will add this to gong, there is an issue created   #206 updates will be posted there!

**Pull request merged**
